services:
  database:
    image: mongo:4.4
    expose:
      - 27017
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodbdata:/data/db
    restart: always
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    command: npm run start
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: "mongodb://database:27017"
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - /home/node/app/server/node_modules/
#      - ./server:/usr/src/app
    depends_on:
      - database
    restart: always
  client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    command: npm run start
    ports:
      - 127.0.0.1:3000:3000
    restart: always
